characters = {
	"1-0-1"	: ["Reimu Hakurei", "Reimu", "Hakurei", "Hakurei Reimu"],
	"1-0-2"	: ["Kirisame Marisa", "Kirisame", "Marisa", "Marisa Kirisame"],
	#"1-0-3"	: ["Reimu Hakurei", "Reimu", "Hakurei", "Hakurei Reimu", "PC-98", "PC-98 Reimu", "PC-98 Hakurei"],
	"1-1"	: ["SinGyoku", "Sin Gyoku", "Sin", "Gyoku"],
	"1-2-A"	: ["YuugenMagan", "Yuugen Magan", "Magan"],
	"1-2-B"	: ["Mima"],
	"1-3-A"	: ["Elis","Ellis","Eris"],
	"1-3-B"	: ["Kikuri"],
	"1-4-A"	: ["Sariel"],
	"1-4-B"	: ["Konngara"],
	"2-1"	: ["Rika"],
	"2-2"	: ["Meira"],
	"2-2-2"	: ["Noroiko"],
	"2-4-2"	: ["Matenshi"],
	#"2-4"	: ["Kirisame Marisa", "Kirisame", "Marisa", "Marisa Kirisame", "PC-98 Marisa", "PC-98 Kirisame"],
	#"2-6"	: ["Rika"], #to do remove 2-6 from save data (I think i did this already I think...)
	"3-1"	: ["Ellen"],
	"3-2"	: ["Kotohime"],
	"3-3"	: ["Kana Anaberal", "Kana", "Anaberal", "Anaberal Kana"],
	"3-4"	: ["Rikako Asakura", "Rikako", "Asakura", "Asakura Rikako"],
	"3-5"	: ["Chiyuri Kitashirakawa", "Chiyuri", "Kitashirakawa", "Kitashirakawa Chiyuri"],
	"3-6"	: ["Okazaki Yumemi", "Yumemi Okazaki", "Yumemi", "Okazaki"],
	"3-EX-1": ["Ruukoto"],
	"4-1"	: ["Orange"],
	"4-2"	: ["Kurumi"],
	"4-3"	: ["Elly"],
	"4-4"	: ["Hikariko"],
	"4-5"	: ["Yuuka Kazami", "Yuuka", "Kazami", "Kazami Yuuka"],
	"4-6-1"	: ["Mugetsu"],
	"4-6-2"	: ["Gengetsu"],
	"5-1"	: ["Sara", "Sala", "Sarah"],
	"5-1-2"	: ["Wayousei"],
	"5-2"	: ["Louise", "Luize"],
	"5-3"	: ["Alice Margatroid", "Alice", "Margatroid", "Margatroid Alice"],
	"5-4-1"	: ["Yuki","Yukki","Yukii"],
	"5-4-2"	: ["Mai"],
	"5-5"	: ["Yumeko", "Red Sakuya"],
	"5-5-2"	: ["Ayana"],
	"5-6"	: ["Shinki"],
	"6-1"	: ["Lumia", "Rumia","Ruumia","Luumia"],
	"6-2"	: ["Cirno","Chiruno","Chillno", "9"],
	"6-2-2"	: ["Daiyousei"],
	"6-3"	: ["Hong Meiling", "Meiling", "Hong", "Meiling Hong", "China"],
	"6-4"	: ["Patchouli Knowledge", "Patchouli", "Knowledge", "Knowledge Patchouli"],
	"6-4-2"	: ["Koakuma"],
	"6-5"	: ["Sakuya Izayoi", "Izayoi Sakuya", "Izayoi", "Sakuya", "Dio"],
	"6-6"	: ["Remilia Scarlet", "Remilia", "Scarlet Remilia"],
	"6-7"	: ["Flandre Scarlet", "Scarlet Flandre", "Flandre", "Flander", "Flander Scarlet", "Flan-chan"],
	"7.5-1"	: ["Suika Ibuki", "Suika", "Ibuki", "Ibuki Suika"],
	"7-1"	: ["Letty Whiterock", "Letty","Whiterock", "Whiterock Letty"],
	"7-2"	: ["Chen"],
	#"7-3"	: ["Alice Margatroid","Alice","Margatroid", "Margatroid Alice"],
	"7-4-1"	: ["Lyrica Prismriver", "Lyrica", "Prismriver Lyrica"],
	"7-4-2"	: ["Lunasa Prismriver", "Lunasa", "Prismriver Lunasa"],
	"7-4-3"	: ["Merlin Prismriver", "Merlin", "Prismriver Merlin"],
	"7-4-4"	: ["Lily White", "White", "Lily"],
	"7-5"	: ["Youmu Konpaku","Youmu", "Konpaku", "Konpaku Youmu"],
	"7-6"	: ["Yuyuko Saigyouji", "Yuyuko", "Saigyouji", "Saigyouji Yuyuko"],
	"7-7"	: ["Yukari Yakumo", "Yukari", "Yakumo Yukari"],
	#"7-7-1"	: ["Yukari Yakumo", "Yukari", "Yakumo Yukari"],
	"7-7-2"	: ["Ran Yakumo", "Ran", "Yakumo Ran"],
	"8-1"	: ["Wriggle Nightbug", "Nightbug", "Wriggle", "WriggleNightbug"],
	"8-2"	: ["Mystia Lorelei", "Mystia", "Lorelei", "Lorelei Mystia"],
	"8-3"	: ["Keine Kamishirasawa", "Keine", "Kamishirasawa", "Kamishirasawa Keine"],
	#"8-3-2"	: ["Keine Kamishirasawa", "Keine", "Kamishirasawa", "Kamishirasawa Keine"],
	"8-5"	: ["Reisen Udongein Inaba", "Reisen", "Udogein", "Inaba"],
	"8-5-2"	: ["Tewi Inaba", "Tewi", "Inaba", "Inaba Tewi"],
	"8-6-A"	: ["Yagokoro Eirin", "Eirin", "Yagokoro", "Eirin Yagokoro"],
	"8-6-B"	: ["Kaguya Houraisan", "Kaguya", "Houraisan", "Houraisan Kaguya"],
	"8-7"	: ["Fujiwara no Mokou", "Fujiwara Mokou", "Fujiwara", "Mokou", "Mokou Fujiwara"],
	"9-1"	: ["Aya Shameimaru", "Shameimaru", "Aya", "Shameimaru Aya"],
	"9-2"	: ["Medicine Melancholy", "Medicine", "Melancholy"],
	#"9-3"	: ["Kazami Yuuka", "Yuuka", "Kazami", "Yuuka Kazami"],
	"9-4"	: ["Komachi Onozuka", "Onozuka", "Komachi", "Onozuka Komachi"],
	"9-5"	: ["Eiki Shiki Yamaxanadu", "EikiShiki Yamaxandu", "EikiShiki", "Yamaxanadu", "ShikiEiki", "ShikiEiki Yamaxandu", "Shiki Eiki Yamaxandu", "Shiki", "Eiki", "Yama"],
	"10-1-1": ["Minoriko Aki", "Aki Minoriko", "Minoriko"],
	"10-1-2": ["Shizuha Aki", "Aki Shizuha", "Shizuha"],
	"10-2"	: ["Hina Kagiyama", "Kagiyama Hina ", "Hina"],
	"10-3"	: ["Nitori Kawashiro", "Kawashiro Nitori", "Nitori"],
	"10-4-2": ["Momiji Inubashiri","Inubashiri Momiji", "Momiji"],
	"10-5"	: ["Sanae Kochiya", "Kochiya Sanae", "Sanae", "Green Reimu"],
	"10-6"	: ["Kanako Yasaka", "Yasaka Kanako", "Kanako"],
	"10-7"	: ["Suwako Moriya", "Moriya Suwako", "Suwako"],
	"10.5-1": ["Tenshi Hinanawi", "Hinanawi Tenshi", "Tenshi"],
	"10.5-2": ["Iku Nagae", "Nagae Iku", "Iku"],
	"11-1-2": ["Kisume", "Bucket"],
	"11-1"	: ["Yamame Kurodani", "Kurodani Yamame", "Yamame"],
	"11-2"	: ["Parsee Mizuhashi", "Mizuhashi Parsee", "Parsee"],
	"11-3"	: ["Yuugi Hoshiguma", "Hoshiguma Yuugi", "Yuugi"],
	"11-4"	: ["Satori Komeiji", "Komeiji Satori", "Satori"],
	"11-5"	: ["Rin Kaenbyou", "Kaenbyou Rin", "Rin", "Orin"],
	"11-6"	: ["Utsuho Reiuji", "Reiuji Utsuho", "Utsuho"],
	"11-7"	: ["Koishi Komeiji", "Komeiji Koishi", "Koishi"],
	"12-1"	: ["Nazrin"],
	"12-2"	: ["Kogasa Tatara", "Tatara Kogasa", "Kogasa"],
	"12-3"	: ["Ichirin Kumoi", "Kumoi Ichirin", "Ichirin"],
	"12-4"	: ["Minamitsu Murasa", "Murasa Minamitsu", "Minamitsu", "Murasa"],
	"12-5"	: ["Shou Toramaru", "Toramaru Shou", "Shou", "Toramaru"],
	"12-6"	: ["Byakuren Hijiri", "Hijiri Byakuren", "Byakuren"],
	"12-7"	: ["Nue Houjuu", "Houjuu Nue", "Nue", "Houjuu", "You must be Nue here"],
	"12.8-A": ["Star Sapphire", "Sapphire Star", "Star"],
	"12.8-B": ["Luna Child", "Child Luna", "Luna"],
	"12.8-C": ["Sunny Milk", "Milk Sunny", "Sunny"],
	"12.5"	: ["Hatate Himekaidou", "Himekaidou Hatate", "Hatate"],
	"13-2"	: ["Kyouko Kasodani", "Kasodani Kyouko", "Kyouko"],
	"13-3"	: ["Yoshika Miyako‎", "Miyako‎ Yoshika", "Yoshika"],
	"13-4"	: ["Seiga Kaku", "Kaku Seiga", "Seiga", "SEGA", "Kaku"],
	"13-5-1": ["Mononobe no Futo", "Futo"],
	"13-5-2": ["Soga no Tojiko", "Tojiko"],
	"13-6"	: ["Toyosatomimi no Miko", "Miko"],
	"13-7"	: ["Mamizou Futatsuiwa", "Futatsuiwa Mamizou", "Mamizou"],
	"13.5-1": ["Hata no Kokoro", "Kokoro"],
	"14-1"	: ["Wakasagihime"],
	"14-2"	: ["Sekibanki"],
	"14-3"	: ["Kagerou Imaizumi", "Imaizumi Kagerou", "Kagerou"],
	"14-4-2": ["Benben Tsukumo", "Tsukumo Benben", "Benben"],
	"14-4-1": ["Yatsuhashi Tsukumo", "Tsukumo Yatsuhashi", "Yatsuhashi"],
	"14-5"	: ["Seija Kijin", "Kijin Seija", "Seija"],
	"14-6"	: ["Shinmyoumaru Sukuna", "Sukuna Shinmyoumaru", "Shinmyoumaru"],
	"14-7"	: ["Raiko Horikawa", "Horikawa Raiko", "Raiko"],
	"14.5-1": ["Kasen Ibaraki", "Ibaraki Kasen", "Kasen"],
	"14.5-2": ["Sumireko Usami", "Usami Sumireko", "Sumireko"],
	"15-1"	: ["Seiran"],
	"15.5-1": ["Shion Yorigami", "Yorigami Shion", "Shion"],
	"15.5-2": ["Joon Yorigami", "Yorigami Joon", "Joon"],
	"15-2"	: ["Ringo"],
	"15-3"	: ["Doremy Sweet", "Sweet Doremy", "Doremy"],
	"15-4"	: ["Sagume Kishin", "Kishin Sagume", "Sagume"],
	"15-5"	: ["Clownpiece"],
	"15-6"	: ["Junko"],
	"15-7"	: ["Hecatia Lapislazuli", "Lapislazuli Hecatia", "Hecatia", "Lapislazuli"],
	"16-1"	: ["Eternity Larva", "Larva Eternity", "Eternity" , "Larva"],
	"16-2"	: ["Nemuno Sakata", "Sakata Nemuno", "Nemuno", "Sakata"],
	"16-3"	: ["Aunn Komano", "Komano Aunn", "Komano", "Aunn"],
	"16-4"	: ["Narumi Yatadera", "Yatadera Narumi", "Yatadera", "Narumi"],
	"16-5-1": ["Mai Teireida", "Teireida Mai", "Teireida", "Mai"],
	"16-5-2": ["Satono Nishida", "Nishida Satono", "Satono", "Nishida"],
	"16-6"	: ["Okina Matara", "Matara Okina", "Okina", "Okina"],
	"17-1"	: ["Eika Ebisu", "Ebisu Eika", "Ebisu", "Eika"],
	"17-2"	: ["Urumi Ushizaki", "Ushizaki Urumi", "Ushizaki", "Urumi"],
	"17-3"	: ["Kutaka Niwatari", "Niwatari Kutaka", "Niwatari", "Kutaka"],
	"17-4"	: ["Yachie Kicchou", "Kicchou Yachie", "Kicchou", "Yachie"],
	"17-5"	: ["Mayumi Joutouguu", "Joutouguu Mayumi", "Mayumi", "Joutouguu"],
	"17-6"	: ["Keiki Haniyasushin", "Haniyasushin Keiki", "Haniyasushin", "Keiki"],
	"17-7"	: ["Saki Kurokoma", "Kurokoma Saki", "Kurokoma" ,"Saki"],
	#"17.5-3": ["Yuugi Hoshiguma", "Hoshiguma Yuugi", "Yuugi"],
	"18-1"	: ["Mike Goutokuji","Mike","Goutokuji","Goutokuji Mike"],
	"18-2"	: ["Takane Yamashiro","Takane","Yamashiro","Yamashiro Takane"],
	"18-3"	: ["Sannyo Komakusa","Sannyo","Komakusa","Komakusa Sannyo"],
	"18-4"	: ["Misumaru Tamatsukuri","Misumaru","Tamatsukuri","Tamatsukuri Misumaru"],
	"18-5"	: ["Megumu Lizunamaru","Lizunamaru Megumu","Megumu","Lizunamaru"],
	"18-5-2": ["Tsukasa Kudamaki","Kudamaki Tsukasa","Tsukasa","Kudamaki"],
	"18-6"	: ["Chimata Tenkyuu"," Chimata","Chimata","Tenkyuu"],
	"18-7"	: ["Momoyo Himemushi","Himemushi Momoyo","Momoyo","Himemushi"],
	"EX-1"	: ["Kosuzu Motoori", "Motoori Kosuzu", "Motoori", "Kosuzu"],
	"EX-2"	: ["Hieda no Akyuu", "Hieda", "Akyuu", "Akyu"],
	"EX-3"	: ["Rin Satsuki", "Satsuki Rin", "Rin", "Satsuki"],
	"EX-4"	: ["Tokiko"],
	"EX-5"	: ["Reisen"],
	"EX-6"	: ["Maribel Hearn", "Maribel", "Hearn"], 	
	"EX-7"	: ["Usami Renko", "Renko Usami", "Renko", "Usami"],
	"EX-8"	: ["Rinnosuke Morichika", "Morichika Rinnosuke", "Morichika", "Rinnosuke"],
	"EX-9"	: ["Fortune Seller"],
	#"EX-10"	: ["Mamizou Futatsuiwa", "Futatsuiwa Mamizou", "Mamizou"],
	"EX-11"	: ["Watatsuki no Yorihime", "Watatsuki" ,"Yorihime"],
	#"EX-12"	: ["Aya shameimaru", "Shameimaru", "Aya", "Shameimaru Aya"],
	"EX-13"	: ["Hisoutensoku"],
	"EX-14"	: ["Youki Konpaku","Youki", "Konpaku", "Konpaku Youki"],
	"EX-15"	: ["Unzan", "Cloud"],
	"EX-16"	: ["Toyohime Watatsuki", "Watatsuki Toyohime", "Watatsuki", "Toyohime"],
	"EX-17" : ["Mimi-Chan", "Mimi"],
	"EX-18"	: ["Shanghai Doll", "Shanghai"],
	"EX-19"	: ["Genji"],
	"EX-20"	: ["Multi"],
	"EX-21"	: ["Makaijin"],
	"EX-22"	: ["Layla Prismriver","Prismriver", "Layla"],
	"EX-23"	: ["Myouren Hijiri","Hijiri Myouren","Hijiri", "Myouren"],
	"EX-24"	: ["Beerko"],
	"EX-25"	: ["Okunoda Miyoi","Miyoi Okunoda","Miyoi","Okunoda"]
	}
	
